# Run static analysis checks
name: Static Analysis

on:
  pull_request:
    branches:
      - v2

jobs:
  analysis:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Run go vet
        run: go vet ./...

      - name: Install and run staticcheck
        run: |
          # add executables installed with go get to PATH
          # TODO: this will hopefully be fixed by
          # https://github.com/actions/setup-go/issues/14
          export PATH=${PATH}:`go env GOPATH`/bin
          go get honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...
